Clean up how colors are formatted

diff --git a/bin/filet b/bin/filet
--- a/bin/filet
+++ b/bin/filet
@@ -1,40 +1,54 @@
 #!/usr/bin/env zsh
 
-COLOR_BLACK="[30m"
-COLOR_RED="[31m"
-COLOR_GREEN="[32m"
-COLOR_YELLOW="[33m"
-COLOR_BLUE="[34m"
-COLOR_MAGENTA="[35m"
-COLOR_CYAN="[36m"
-COLOR_WHITE="[37m"
-COLOR_BRIGHT_BLACK="[30;1m"
-COLOR_BRIGHT_RED="[31;1m"
-COLOR_BRIGHT_GREEN="[32;1m"
-COLOR_BRIGHT_YELLOW="[33;1m"
-COLOR_BRIGHT_BLUE="[34;1m"
-COLOR_BRIGHT_MAGENTA="[35;1m"
-COLOR_BRIGHT_CYAN="[36;1m"
-COLOR_BRIGHT_WHITE="[37;1m"
-COLOR_RESET="[0m"
-COLOR_DIM="[2m"
-COLOR_DIM_RESET="[22m"
+autoload -U colors
+colors
+
+color_format() (
+  string="${@}"
+  stack=(default)
+  
+  while [[ "${string}" =~ '{{([^}]+)}}' ]]; do
+    echo -n "${string:0:($MBEGIN - 1)}"
+
+    color="${match[1]}"
+    if [[ "${color}" == "/" ]]; then
+      current="${stack[-1]}"
+      shift -p stack
+      if [[ "${current}" == "dim" ]]; then
+        echo -n "[22m"
+      else
+        color="${stack[-1]}"
+      fi
+    else
+      stack+=("${color}")
+    fi
+
+    if [[ "${color}" == "dim" ]]; then
+      echo -n "[2m"
+    else
+      echo -n "${fg[$color]}"
+    fi
+
+    string="${string:$MEND}"
+  done
+  echo -n "${string}"
+)
 
 log() (
-  echo "$@" >&2
+  echo $(color_format "$@[0m") >&2
 )
 
 log_debug() (
   if [[ ! -v FILET_VERBOSE ]]; then return; fi
-  echo "${COLOR_DIM}$@${COLOR_DIM_RESET}"
+  echo "{{dim}}$@"
 )
 
 log_warn() (
-  log "${COLOR_YELLOW}$@${COLOR_RESET}" 
+  log "{{yellow}}@" 
 )
 
 log_error() (
-  log "${COLOR_RED}$@${COLOR_RESET}" 
+  log "{{red}}$@" 
 )
 
 fail() (
@@ -45,7 +59,7 @@ evaluate_script() {
   script="${1}"
 
   if [[ ! -f "${script}" ]]; then
-    fail "Can't locate filet script ${COLOR_MAGENTA}${script}${COLOR_RED} (${COLOR_MAGENTA}${script:A}${COLOR_RED})"
+    fail "Can't locate filet script {{magenta}}${script}{{/}} ({{magenta}}${script:A}{{/}})"
   fi
   
   if [[ ! -v FILET_SCRIPT_ENVIRONMENT_LOADED ]]; then
@@ -66,7 +80,7 @@ evaluate_script() {
 }
 
 command_apply_help() (
-  log "Usage: ${COLOR_CYAN}filet ${COLOR_YELLOW}apply ${COLOR_MAGENTA}file.filet${COLOR_RESET}"
+  log "Usage: {{cyan}}filet{{/}} {{yellow}}apply{{/}} {{magenta}}file.filet{{/}}"
 )
 
 command_apply_main() (
@@ -85,11 +99,11 @@ command_help_main() (
   if [[ "${command}" == "" ]]; then
     default_help
   elif ! is_function "command_${command}_main"; then
-    log_error "Unknown command: ${COLOR_YELLOW}${command}${COLOR_RESET}"
+    log_error "Unknown command: {{yellow}}${command}{{/}}"
     log
     default_help
   elif ! is_function "command_${command}_help"; then
-    log_error "The ${COLOR_YELLOW}${command}${COLOR_RED} command failed to implement command_${command}_help"
+    log_error "The {{yellow}}${command}{{/}} command failed to implement command_${command}_help"
     log
     default_help
   else
@@ -100,7 +114,7 @@ command_help_main() (
 )
 
 default_help() (
-  log "Usage: ${COLOR_CYAN}filet ${COLOR_YELLOW}command${COLOR_RESET}"
+  log "Usage: {{cyan}}filet{{/}} {{yellow}}command{{/}}"
 )
 
 main() (
